<?php
/*
 * jQuery Mobile Framework : plugin to provide a date and time picker.
 * Copyright (c) JTSage
 * CC 3.0 Attribution.  May be relicensed without permission/notification.
 * https://github.com/jtsage/jquery-mobile-datebox
 */
/* Options Documentation */

$text = array(
	'common' => array( 'Common Options', array(
		'mode' => "Choose the mode of operation of datebox - 'datebox', 'timebox', 'calbox', 'flipbox', 'timeflipbox', 'durationbox', 'durationflipbox', or 'slidebox'",
		'lockInput' => "Lock the original input element, disallowing direct user input - i.e. force the use of the control",
		'enhanceInput' => "In internal control inputs, enhance the fields to only allow numeric input.  Handy for use in mobile, as it should pop up a numeric keypad rather than a full keyboard.  Somewhat less useful on tablet and desktop devices, as the input methods are usually identical",
		'defaultValue' => "Set the default date value, or time value.  Date should be supplied as a three element array [year, month, date] - time can be supplied as a 24hr string '15:41'",
		'showInitialValue' => "Auto-fill the input on datebox initilization - this will take into account any default value options",
		'startOffsetYears' => "Offset the start year by X number of years.  This valuye will be added to 'defaultValue' if it is supplied",
		'startOffsetMonths' => "Offset the start month by X number of months.  This valuye will be added to 'defaultValue' if it is supplied",
		'startOffsetDays' => "Offset the start day by X number of days.  This valuye will be added to 'defaultValue' if it is supplied"
	)),
	'display' => array('Display Options', array(
		'centerHoriz' => "When using datebox popup mode, force the control to center horizontally in the window rather than over the input element",
		'centerVert' => "When using datebox popup mode, force the control to center vertically in the window rather then over the input element",
		'transition' => "Transition to use on datebox popup, jqm popup, and dialog display modes",
		'useAnimation' => "Enable or disable animations - since datebox does not truly 'close' until animation is complete, this may be useful when trying to automate inputs",
		'hideInput' => "Cause the original input to be hidden on the page",
		'hideFixedToolbars' => "Hide fixed toolbars (if enabled) when the control opens.  Note this may be buggy on some platforms",
		'zindex' => "The Zindex to use for the datebox control.  If applicable, there is a full-screen overlay behind the control at zIndex-1",
		'clickEvent' => "Listener event for all non-close-action buttons in the control",
		'clickEventAlt' => "Listener event for all close-action buttons in the control",
		'resizeListener' => "Re-calculate positioning when the screen size changes - for instance when flipping from portrait to landscape mode. This only applies to datebox popup mode",
		'dialogEnable' => "Allow the use of jqm builtin dialog mode.  When not forced, dialog will be enabled when screen size is less than 400px",
		'dialogForce' => "Force datebox to always use jqm builtin dialog mode.",
		'enablePopup' => "Enable the use of jqm builtin popup mode rather than the datebox native one",
		'popupForceX' => "Force the X position of the jqm builtin popup mode. (top left corner)",
		'popupForceY' => "Force the Y position of the jqm builtin popup mode. (top left corner)",
		'popupPosition' => "Control how the jqm builtin popup mode positions.  Set to 'window' to center in the open window.  Set to an '#id' to center over that element. When set to false, allow datebox to center over the input element",
		'useModal' => "When using datebox popup mode, shade the background and force input to the control",
		'useInline' => "Show control inline in the page, negating any open and close actions",
		'useInlineBlind' => "Attach the control directly to the input element, and roll it down from there when opened",
		'useButton' => "Display an open button inside the input element that will open the control",
		'useFocus' => "Open datebox control when input element is focused (and disable button)",
		'usePlaceholder' => "Auto-fill the placeholder text from the input element's label if set to true.  Or, set to a string and it will use that text to set the placeholder",
		'useNewStyle' => "Use the 'new' style for the input element - recommended, much, much cleaner",
		'useAltIcon' => "When using 'useNewStyle', use a light colored icon instead of a dark one",
		'overrideStyleClass' => "When using 'useNewStyle', override the default icon scheme with a css class of your own.  Usefull if you need more than a single style of datebox icon - otherwise, just override the css",
	)),
	'control' => array('Control Options', array(
		'useHeader' => array(true, 'Use a toolbar header for the control', 'Boolean', true),
		'useImmediate' => array(false, 'Update the Input Element on every control change', 'Boolean', true),
		'useClearButton' => array(false, 'Show a button to clear the Input Element in the control', 'Boolean', true),
		'useSetButton' => array(true, 'Show button to set the date', 'Boolean', array(1,0,1,1,1,1,1)),
		'useTodayButton' => array(false, 'Show button to jump to today', 'Boolean', array(0,1,0,0,0,0,0)),
		'useCollapsedBut' => array(false, 'When 2 buttons would show, collapse them into a single line', 'Boolean', true),
		'rolloverMode' => array("{ 'm': true, 'd': true, 'h': true, 'i': true, 's': true }", 'Allow rollover of each date element', 'Object', array(1,0,1,1,1,1,0)),
		'slen' => array("{'y': 5, 'm':6, 'd':15, 'h':12, 'i':30}", 'Length of sliders (1/2 of slider)', 'Object', array(0,0,0,1,0,0,0)),
		'flen' => array("{'y': 15, 'm':12, 'd':15, 'h':12, 'i':15, 'a':3}", 'Height of rollers (1/2 of roller)', 'Object', array(0,0,1,0,0,1,0)),
		'calShowDays' => array(true, 'Show Day Labels in calendar', 'Boolean', array(0,1,0,0,0,0,0)),
		'calShowWeek' => array(false, 'Show ISO Week number in calendar', 'Boolean', array(0,1,0,0,0,0,0)),
		'calOnlyMonth' => array(false, 'Do not show next/previous months in calendar', 'Boolean', array(0,1,0,0,0,0,0)),
		'calWeekMode' => array(false, 'Select by single week day in calendar', 'Boolean', array(0,1,0,0,0,0,0)),
		'calWeekModeDay' => array(1, 'Weekday to select when in calWeekMode', 'Integer', array(0,1,0,0,0,0,0))
	)),
	'limiting' => array('Data Limiting Options', array(
		'afterToday' => array(false, 'Limit all dates selected to *after* today\'s date', 'Boolean', array(1,1,1,1,0,0,0)),
		'beforeToday' => array(false, 'Limit all dates selected to *before* today\'s date', 'Boolean', array(1,1,1,1,0,0,0)),
		'notToday' => array(false, 'Limit all dates selected to *not* today\'s date', 'Boolean', array(1,1,1,1,0,0,0)),
		'maxDays' => array(false, 'Limit all dates selected to before today + ## days', 'Integer', array(1,1,1,1,0,0,0)),
		'minDays' => array(false, 'Limit all dates selected to after today - ## days', 'Integer', array(1,1,1,1,0,0,0)),
		'maxYear' => array(false, 'Limit all dates selected to before this year', 'Integer', array(1,0,1,1,0,0,0)),
		'minYear' => array(false, 'Limit all dates selected to after this year', 'Integer', array(1,0,1,1,0,0,0)),
		'blackDatesRec' => array(false, 'Do not allow these recurring dates to be selected (array of arrays)', 'Array', array(1,1,1,1,0,0,0)),
		'blackDates' => array(false, 'Do not allow these ISO dates to be selected (array of dates)', 'Array', array(1,1,1,1,0,0,0)),
		'blackDays' => array(false, 'Do not allow these days to be selected (array of day indexes)', 'Array', array(1,1,1,1,0,0,0)),
		'enableDates' => array(false, 'Allow *only* these ISO dates to be sleected (array of dates)', 'Array', array(0,1,0,0,0,0,0)),
		'minHour' => array(false, 'Limit times to hours *after* this hour', 'Integer', array(0,0,0,0,1,1,0)),
		'maxHour' => array(false, 'Limit times to hours *before* this hour', 'Integer', array(0,0,0,0,1,1,0)),
		'validHours' => array(false, 'Limit times to *only* these hours (array of hours)', 'Array', array(0,0,0,0,1,1,0)),
		'minuteStep' => array(1, 'Stepper for minutes', 'Integer', array(0,0,0,1,1,1,0)),
		'minuteStepRound' => array(0, 'Direction to round :: -1 = Down, 1 = Up, 0 = "Standard Rounding"', 'Integer', array(0,0,0,1,1,1,0)),
		'highDays' => array(false, 'Highlight these days (array of day indexes)', 'Array', array(0,1,0,0,0,0,0)),
		'highDates' => array(false, 'Highlight these ISO dates (array of dates)', 'Array', array(0,1,0,0,0,0,0)),
		'highDatesRec' => array(false, 'Highlight these recurring dates (array of arrays)', 'Array', array(0,1,0,0,0,0,0)),
		'highDatesAlt' => array(false, 'Highlight these ISO dates (array of dates) (alternate)', 'Array', array(0,1,0,0,0,0,0)),
		'calShowDateList' => array(false, 'Show Special Date List Picker', 'Boolean', array(0,1,0,0,0,0,0)),
		'calDateList' => array(false, 'Array of 2 Element Arrays (each w/ an ISO date and a desc)', 'Array', array(0,1,0,0,0,0,0)),
		'durationSteppers' => array("{'d': 1, 'h': 1, 'i': 1, 's': 1}", 'Steppers for the duration elements', 'Object', array(0,0,0,0,0,0,1))
	)),
	'themes' => array('Theme Options', array(
		'theme' => array(false, 'Base theme for control', 'Boolean', true),
		'themeHeader' => array('a', 'Theme for header', 'String', true),
		'themeButton' => array('a', 'Theme swatch for +/- Buttons', 'String', array(1,0,0,0,1,0,1)),
		'themeInput' => array('e', 'Theme swatch for input elements', 'String', array(1,0,0,0,1,0,1)),
		'themeDateHigh' => array('e', 'Theme swatch for today\'s date', 'String', array(0,1,1,1,0,1,0)),
		'themeDatePick' => array('a', 'Theme swatch for choosen (centered) date', 'String', array(0,1,1,1,0,1,0)),
		'themeDate' => array('d', 'Theme swatch for other dates', 'String', array(0,1,1,1,0,1,0)),
		'themeDateToday' => array('a', 'Theme swatch for today\'s date', 'String', array(0,1,0,0,0,0,0)),
		'themeDayHigh' => array('e', 'Theme swatch for highDays', 'String', array(0,1,0,0,0,0,0)),
		'themeDateHighAlt' => array('e', 'Theme swatch for highDatesAlt', 'String', array(0,1,0,0,0,0,0)),
		'themeDateHighRec' => array('e', 'Theme swatch for highDatesRec', 'String', array(0,1,0,0,0,0,0)),
		'calUsePickers' => array(false, 'Use Month/Year Pickers', 'Boolean', array(0,1,0,0,0,0,0)),
		'calYearPickMin' => array(-6, 'Limit for Year Picker (Int < 1800, Year, "NOW")', 'Mixed', array(0,1,0,0,0,0,0)),
		'calYearPickMax' => array(6, 'Limit for Year Picker (Int < 1800, Year, "NOW")', 'Mixed', array(0,1,0,0,0,0,0)),
		'calNoHeader' => array(false, 'Suppress Standard Header', 'Boolean', array(0,1,0,0,0,0,0)),
		'calHighToday' => array(true, 'Highlight today\'s date', 'Boolean', array(0,1,0,0,0,0,0)),
		'calHighPick' => array(true, 'Highlight choosen date', 'Boolean', array(0,1,0,0,0,0,0)),
		'calWeekHigh' => array(false, 'Highlight full week on mouseover', 'Boolean', array(0,1,0,0,0,0,0)),
		'calControlGroup' => array(false, 'Use control group buttons in calendar', 'Boolean', array(0,1,0,0,0,0,0))
	)),
	'i18n' => array('Internationalization Options (overrideOptionName)', array(
		'setDateButtonLabel' => array('Set Date', 'Set Date Button Label', 'String', array(1,1,1,1,0,0,0)),
		'setTimeButtonLabel' => array('Set Time', 'Set Time Button Label', 'String', array(0,0,0,0,1,1,0)),
		'setDurationButtonLabel' => array('Set Duration', 'Set Duration Button Label', 'String', array(0,0,0,0,0,0,1)),
		'calTodayButtonLabel' => array('Jump to Today', 'Jump to today button Label', 'String', array(0,1,0,0,0,0,0)),
		'titleDateDialogLabel' => array('Set Date', 'Date modes fallback header label', 'String', array(1,1,1,1,0,0,0)),
		'titleTimeDialogLabel' => array('Set Time', 'Time modes fallback header label', 'String', array(0,0,0,0,1,1,1)),
		'daysOfWeek' => array("array('Sunday' ... 'Saturday']", 'Days of the week', 'Array', true),
		'daysOfWeekShort' => array("array('Su' ... 'Sa']", 'Abbreviated days of the week', 'Array', true),
		'monthsOfYear' => array("array('January' ... 'December']", 'Months of the year', 'Array', true),
		'monthsOfYearShort' => array("array('Jan' ... 'Dec']", 'Abbreviated months of the year', 'Array', true),
		'durationLabel' => array("array('Days', 'Hours', 'Minutes', 'Seconds']", 'Labels for duration elements', 'Array', array(0,0,0,0,0,0,1)),
		'durationDays' => array("array('Day', 'Days']", 'Name of day/days for duration', 'Array', array(0,0,0,0,0,0,1)),
		'timeFormat' => array(24, 'Format for clock', 'Integer', array(0,0,0,0,1,1,0)),
		'headerFormat' => array('%A, %B %-d, %Y', 'Format for header if used', 'String', true),
		'tooltip' => array('Open Date Picker', 'Mouseover tooltip for open button', 'String', true),
		'nextMonth' => array('Next Month', 'Mouseover tooltip for next month button', 'String', array(0,1,0,0,0,0,0)),
		'prevMonth' => array('Previous Month', 'Mouseover tooltip for prev month button', 'String', array(0,1,0,0,0,0,0)),
		'dateFieldOrder' => array("array('m', 'd', 'y']", 'Field order for date entry', 'Array', array(1,0,1,0,0,0,0)),
		'timeFieldOrder' => array("array('h', 'i', 'a']", 'Field order for time entry', 'Array', array(0,0,0,0,1,1,0)),
		'slideFieldOrder' => array("array('y', 'm', 'd']", 'Field order for slide mode', 'Array', array(0,0,0,1,0,0,0)),
		'dateFormat' => array('%Y-%m-%d', 'Format for returned date', 'Array', array(1,1,1,1,0,0,0)),
		'useArabicIndic' => array(false, 'Use Arabic/Indic numerals', 'Boolean', true),
		'isRTL' => array(false, 'Language runs Right-to-Left', 'Boolean', true),
		'calStartDay' => array(0, 'Day of week to start calendar on', 'Integer', array(0,1,0,0,0,0,0)),
		'clearButton' => array('Clear', 'Clear Input Element button label', 'String', true),
		'durationOrder' => array("array('d', 'h', 'i', 's']", 'Field order for duration entry', 'Array', array(0,0,0,0,0,0,1)),
		'meridiem' => array("array('AM', 'PM']", 'Name of meridiems, if used', 'Array', true),
		'timeOutput' => array('%k:%M', 'Format for returned time', 'String', array(0,0,0,0,1,1,0)),
		'durationFormat' => array('%Dd %DA, %Dl:%DM:%DS', 'Format for returned duration', 'String', array(0,0,0,0,0,0,1)),
		'calDateListLabel' => array('Other Dates', 'Text for other dates dropdown', 'String', array(0,1,0,0,0,0,0)),
		'calHeaderFormat' => array('%B %Y', 'Header format for calendar mode', 'String', array(0,1,0,0,0,0,0)),
		'calTomorrowButtonLabel' => array('Jump to Tommorrow', 'Text for "tommorrow" button', 'String', array(0,1,0,0,0,0,0))
	)),
	'custom' => array('CustomBox/CustomFlip Options', array(
		'customData' => array('N/A', 'Data structure for custom modes', 'Array', false),
		'themeOptPick' => array('a', 'Theme for highlighted option (customflip)', 'String', false),
		'themeOpt' => array('d', 'Theme for other options (customflip)', 'String', false),
		'overrideCustomSet' => array('Looks Good', 'Set button for custom modes (i18n aware)', 'String', false),
		'customDefault' => array('[0,0,0]', 'Array of default indexs for custom modes', 'Array', false)
	)),
	'callback' => array('Callback Options', array(
		'openCallback' => array(false, 'Callback function to run on control open', 'Function', true),
		'openCallbackArgs' => array("[]", 'Extra arguments to pass to open callback.', 'Array', true),
		'closeCallback' => array(false, 'Callback function to run on control close', 'Function', true),
		'closeCallbackArgs' => array("[]", 'Extra arguments to pass to close callback.', 'Array', true)
	)),
	'public' => array('Public Functions', array(
		'open' => array('', 'Open the datebox control', 'Function'),
		'close' => array('', 'Close the datebox control', 'Function'),
		'disable' => array('', 'Disable the datebox control', 'Function'),
		'enable' => array('', 'Enable the datebox control', 'Function'),
		'refresh' => array('', 'Refresh the datebox control', 'Function'),
		'getTheDate' => array('', 'Return the current date object', 'Function'),
		'setTheDate' => array('', 'Set the date (date object)', 'Function'),
		'getLastDur' => array('', 'Get the last set duration', 'Function'),
		'{}' => array('', 'Set an option', 'Function'),
		'getOption' => array('', "Retrieve an option's value", 'Function'),
		'callFormat' => array('', 'Return a formatted date', 'Function'),
		'applyMinMax' => array('', 'Apply new min/max attributes', 'Function')
	)),
);
?>
